DROP TABLE IF EXISTS notes CASCADE;
-- CREATE USERS
CREATE TABLE notes (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255),
  body TEXT NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);